require 'win-ffi/user32'

module WinFFI
  module User32
    # https://msdn.microsoft.com/en-us/library/windows/desktop/ms724947%28v=vs.85%29.aspx
    SystemParametersInfoFlag = enum :system_parameters_info_flag,
    [
      :GETACCESSTIMEOUT,            0x003C,
      :GETAUDIODESCRIPTION,         0x0074,
      :GETCLIENTAREAANIMATION,      0x1042,
      :GETDISABLEOVERLAPPEDCONTENT, 0x1040,
      :GETFILTERKEYS,               0x0032,
      :GETFOCUSBORDERHEIGHT,        0x2010,
      :GETFOCUSBORDERWIDTH,         0x200E,
      :GETHIGHCONTRAST,             0x0042,
      :GETLOGICALDPIOVERRIDE,       0x009E,
      :GETMESSAGEDURATION,          0x2016,
      :GETMOUSECLICKLOCK,           0x101E,
      :GETMOUSECLICKLOCKTIME,       0x2008,
      :GETMOUSEKEYS,                0x0036,
      :GETMOUSESONAR,               0x101C,
      :GETMOUSEVANISH,              0x1020,
      :GETSCREENREADER,             0x0046,
      :GETSERIALKEYS,               0x003E,
      :GETSHOWSOUNDS,               0x0038,
      :GETSOUNDSENTRY,              0x0040,
      :GETSTICKYKEYS,               0x003A,
      :GETTOGGLEKEYS,               0x0034,
      :SETACCESSTIMEOUT,            0x003D,
      :SETAUDIODESCRIPTION,         0x0075,
      :SETCLIENTAREAANIMATION,      0x1043,
      :SETDISABLEOVERLAPPEDCONTENT, 0x1041,
      :SETFILTERKEYS,               0x0033,
      :SETFOCUSBORDERHEIGHT,        0x2011,
      :SETFOCUSBORDERWIDTH,         0x200F,
      :SETHIGHCONTRAST,             0x0043,
      :SETLOGICALDPIOVERRIDE,       0x009F, # Do not use.
      :SETMESSAGEDURATION,          0x2017,
      :SETMOUSECLICKLOCK,           0x101F,
      :SETMOUSECLICKLOCKTIME,       0x2009,
      :SETMOUSEKEYS,                0x0037,
      :SETMOUSESONAR,               0x101D,
      :SETMOUSEVANISH,              0x1021,
      :SETSCREENREADER,             0x0047,
      :SETSERIALKEYS,               0x003F,
      :SETSHOWSOUNDS,               0x0039,
      :SETSOUNDSENTRY,              0x0041,
      :SETSTICKYKEYS,               0x003B,
      :SETTOGGLEKEYS,               0x0035,

      # The following are the desktop parameters.
      :GETCLEARTYPE,                0x1048,
      :GETDESKWALLPAPER,            0x0073,
      :GETDROPSHADOW,               0x1024,
      :GETFLATMENU,                 0x1022,
      :GETFONTSMOOTHING,            0x004A,
      :GETFONTSMOOTHINGCONTRAST,    0x200C,
      :GETFONTSMOOTHINGORIENTATION, 0x2012,
      :GETFONTSMOOTHINGTYPE,        0x200A,
      :GETWORKAREA,                 0x0030,
      :SETCLEARTYPE,                0x1049,
      :SETCURSORS,                  0x0057,
      :SETDESKPATTERN,              0x0015,
      :SETDESKWALLPAPER,            0x0014,
      :SETDROPSHADOW,               0x1025,
      :SETFLATMENU,                 0x1023,
      :SETFONTSMOOTHING,            0x004B,
      :SETFONTSMOOTHINGCONTRAST,    0x200D,
      :SETFONTSMOOTHINGORIENTATION, 0x2013,
      :SETFONTSMOOTHINGTYPE,        0x200B,
      :SETWORKAREA,                 0x002F,

      # The following are the icon parameters.
      :GETICONMETRICS,              0x002D,
      :GETICONTITLELOGFONT,         0x001F,
      :GETICONTITLEWRAP,            0x0019,
      :ICONHORIZONTALSPACING,       0x000D,
      :ICONVERTICALSPACING,         0x0018,
      :SETICONMETRICS,              0x002E,
      :SETICONS,                    0x0058,
      :SETICONTITLELOGFONT,         0x0022,
      :SETICONTITLEWRAP,            0x001A,
      :GETBEEP,                     0x0001,
      :GETBLOCKSENDINPUTRESETS,     0x1026,
      :GETCONTACTVISUALIZATION,     0x2018,
      :GETDEFAULTINPUTLANG,         0x0059,
      :GETGESTUREVISUALIZATION,     0x201A,
      :GETKEYBOARDCUES,             0x100A,
      :GETKEYBOARDDELAY,            0x0016,
      :GETKEYBOARDPREF,             0x0044,
      :GETKEYBOARDSPEED,            0x000A,
      :GETMOUSE,                    0x0003,
      :GETMOUSEHOVERHEIGHT,         0x0064,
      :GETMOUSEHOVERTIME,           0x0066,
      :GETMOUSEHOVERWIDTH,          0x0062,
      :GETMOUSESPEED,               0x0070,
      :GETMOUSETRAILS,              0x005E,
      :GETSNAPTODEFBUTTON,          0x005F,
      :GETSYSTEMLANGUAGEBAR,        0x1050,
      :GETTHREADLOCALINPUTSETTINGS, 0x104E,
      :GETWHEELSCROLLCHARS,         0x006C,
      :GETWHEELSCROLLLINES,         0x0068,
      :SETBEEP,                     0x0002,
      :SETBLOCKSENDINPUTRESETS,     0x1027,
      :SETCONTACTVISUALIZATION,     0x2019,
      :SETDEFAULTINPUTLANG,         0x005A,
      :SETDOUBLECLICKTIME,          0x0020,
      :SETDOUBLECLKHEIGHT,          0x001E,
      :SETDOUBLECLKWIDTH,           0x001D,
      :SETGESTUREVISUALIZATION,     0x201B,
      :SETKEYBOARDCUES,             0x100B,
      :SETKEYBOARDDELAY,            0x0017,
      :SETKEYBOARDPREF,             0x0045,
      :SETKEYBOARDSPEED,            0x000B,
      :SETLANGTOGGLE,               0x005B,
      :SETMOUSE,                    0x0004,
      :SETMOUSEBUTTONSWAP,          0x0021,
      :SETMOUSEHOVERHEIGHT,         0x0065,
      :SETMOUSEHOVERTIME,           0x0067,
      :SETMOUSEHOVERWIDTH,          0x0063,
      :SETMOUSESPEED,               0x0071,
      :SETMOUSETRAILS,              0x005D,
      :SETSNAPTODEFBUTTON,          0x0060,
      :SETSYSTEMLANGUAGEBAR,        0x1051,
      :SETTHREADLOCALINPUTSETTINGS, 0x104F,
      :SETWHEELSCROLLCHARS,         0x006D,
      :SETWHEELSCROLLLINES,         0x0069,

      # The following are the menu parameters.
      :GETMENUDROPALIGNMENT, 0x001B,
      :GETMENUFADE,          0x1012,
      :GETMENUSHOWDELAY,     0x006A,
      :SETMENUDROPALIGNMENT, 0x001C,
      :SETMENUFADE,          0x1013,
      :SETMENUSHOWDELAY,     0x006B,

      # The following are the power parameters.
      # Beginning with Windows Server 2008 and Windows Vista, these power parameters are not supported. Instead, to
      # determine the current display power state, an application should register for GUID_MONITOR_POWER_STATE
      # notifications. To determine the current display power down time-out, an application should register for
      # notification of changes to the GUID_VIDEO_POWERDOWN_TIMEOUT power setting. For more information, see
      # Registering for Power Events.
      # Windows Server 2003 and Windows XP/2000:  To determine the current display power state, use the following
      # power parameters.

      :GETLOWPOWERACTIVE,  0x0053,
      :GETLOWPOWERTIMEOUT, 0x004F,
      :GETPOWEROFFACTIVE,  0x0054,
      :GETPOWEROFFTIMEOUT, 0x0050,
      :SETLOWPOWERACTIVE,  0x0055,
      :SETLOWPOWERTIMEOUT, 0x0051,
      :SETPOWEROFFACTIVE,  0x0056,
      :SETPOWEROFFTIMEOUT, 0x0052,

      # The following are the screen saver parameters.
      :GETSCREENSAVEACTIVE,   0x0010,
      :GETSCREENSAVERRUNNING, 0x0072,
      :GETSCREENSAVESECURE,   0x0076,
      :GETSCREENSAVETIMEOUT,  0x000E,
      :SETSCREENSAVEACTIVE,   0x0011,
      :SETSCREENSAVESECURE,   0x0077,
      :SETSCREENSAVETIMEOUT,  0x000F,

      # The following are the time-out parameters for applications and services.
      :GETHUNGAPPTIMEOUT,           0x0078,
      :GETWAITTOKILLTIMEOUT,        0x007A,
      :GETWAITTOKILLSERVICETIMEOUT, 0x007C,
      :SETHUNGAPPTIMEOUT,           0x0079,
      :SETWAITTOKILLTIMEOUT,        0x007B,
      :SETWAITTOKILLSERVICETIMEOUT, 0x007D,

      # The following are the UI effects. The :SETUIEFFECTS value is used to enable or disable all UI effects at once.
      # This table contains the complete list of UI effect values.
      :GETCOMBOBOXANIMATION,      0x1004,
      :GETCURSORSHADOW,           0x101A,
      :GETGRADIENTCAPTIONS,       0x1008,
      :GETHOTTRACKING,            0x100E,
      :GETLISTBOXSMOOTHSCROLLING, 0x1006,
      :GETMENUANIMATION,          0x1002,
      :GETMENUUNDERLINES,         0x100A,
      :GETSELECTIONFADE,          0x1014,
      :GETTOOLTIPANIMATION,       0x1016,
      :GETTOOLTIPFADE,            0x1018,
      :GETUIEFFECTS,              0x103E,
      :SETCOMBOBOXANIMATION,      0x1005,
      :SETCURSORSHADOW,           0x101B,
      :SETGRADIENTCAPTIONS,       0x1009,
      :SETHOTTRACKING,            0x100F,
      :SETLISTBOXSMOOTHSCROLLING, 0x1007,
      :SETMENUANIMATION,          0x1003,
      :SETMENUUNDERLINES,         0x100B,
      :SETSELECTIONFADE,          0x1015,
      :SETTOOLTIPANIMATION,       0x1017,
      :SETTOOLTIPFADE,            0x1019,
      :SETUIEFFECTS,              0x103F,

      # The following are the window_class parameters.
      :GETACTIVEWINDOWTRACKING,   0x1000,
      :GETACTIVEWNDTRKZORDER,     0x100C,
      :GETACTIVEWNDTRKTIMEOUT,    0x2002,
      :GETANIMATION,              0x0048,
      :GETBORDER,                 0x0005,
      :GETCARETWIDTH,             0x2006,
      :GETDOCKMOVING,             0x0090,
      :GETDRAGFROMMAXIMIZE,       0x008C,
      :GETDRAGFULLWINDOWS,        0x0026,
      :GETFOREGROUNDFLASHCOUNT,   0x2004,
      :GETFOREGROUNDLOCKTIMEOUT,  0x2000,
      :GETMINIMIZEDMETRICS,       0x002B,
      :GETMOUSEDOCKTHRESHOLD,     0x007E,
      :GETMOUSEDRAGOUTTHRESHOLD,  0x0084,
      :GETMOUSESIDEMOVETHRESHOLD, 0x0088,
      :GETNONCLIENTMETRICS,       0x0029,
      :GETPENDOCKTHRESHOLD,       0x0080,
      :GETPENDRAGOUTTHRESHOLD,    0x0086,
      :GETPENSIDEMOVETHRESHOLD,   0x008A,
      :GETSHOWIMEUI,              0x006E,
      :GETSNAPSIZING,             0x008E,
      :GETWINARRANGING,           0x0082,
      :SETACTIVEWINDOWTRACKING,   0x1001,
      :SETACTIVEWNDTRKZORDER,     0x100D,
      :SETACTIVEWNDTRKTIMEOUT,    0x2003,
      :SETANIMATION,              0x0049,
      :SETBORDER,                 0x0006,
      :SETCARETWIDTH,             0x2007,
      :SETDOCKMOVING,             0x0091,
      :SETDRAGFROMMAXIMIZE,       0x008D,
      :SETDRAGFULLWINDOWS,        0x0025,
      :SETDRAGHEIGHT,             0x004D,
      :SETDRAGWIDTH,              0x004C,
      :SETFOREGROUNDFLASHCOUNT,   0x2005,
      :SETFOREGROUNDLOCKTIMEOUT,  0x2001,
      :SETMINIMIZEDMETRICS,       0x002C,
      :SETMOUSEDOCKTHRESHOLD,     0x007F,
      :SETMOUSEDRAGOUTTHRESHOLD,  0x0085,
      :SETMOUSESIDEMOVETHRESHOLD, 0x0089,
      :SETNONCLIENTMETRICS,       0x002A,
      :SETPENDOCKTHRESHOLD,       0x0081,
      :SETPENDRAGOUTTHRESHOLD,    0x0087,
      :SETPENSIDEMOVETHRESHOLD,   0x008B,
      :SETSHOWIMEUI,              0x006F,
      :SETSNAPSIZING,             0x008F,
      :SETWINARRANGING,           0x0083
    ]
  end
end